apiVersion: v1
data:
    username: bW92ZXpkYg==  # echo -n beyond08 | base64
    password: c3Ryb25ncGFzc3dvcmQ= # echo -n beyond08 | base64
    database: bW92ZXo=  # echo -n todolist | base64
kind: Secret
metadata:
    name: db-credentials
