# Use the Postgres image with PostGIS preinstalled
FROM postgis/postgis:latest

# Set environment variables (replace with your own values)
ENV POSTGRES_USER=movezdb
ENV POSTGRES_PASSWORD=strongpassword
ENV POSTGRES_DB=movez

# cd .\k8s\
# docker build -t  postgis-preist .
#docker run -p 5432:5432 -v C:\Users\USER\Documents\ComputerScience\fourthYear\B\db:/var/lib/postgresql/data postgis-preist